services:
  docono.communication.slack:
    class: docono\CommunicationBundle\Services\Slack
  docono.communication.form:
    class: docono\CommunicationBundle\Services\Form
    arguments: ['@translator', '@request_stack', '@form.factory']